/* eslint-disable no-irregular-whitespace */

import { Email } from ".";
import { EmailStyle as Style, EmailType as Type } from "./types";

export interface EmailTemplate {
  type: Type,
  style: Style,
  language: string,
}

interface SimpleTemplateMatcher extends EmailTemplate {
  subject: RegExp,
}

interface ComplicatedEmailMatcher {
  subject: RegExp,
  disambiguate?: (email: Email) => EmailTemplate | null,
}

type AnyEmailTemplate = SimpleTemplateMatcher | ComplicatedEmailMatcher;

const TEMPLATES: AnyEmailTemplate[] = [
//  ---------------------------------------- MISCELLANEOUS ----------------------------------------
  {
    subject: /^Ingress Mission/,
    type: Type.MISCELLANEOUS,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Ingress Damage Report:/,
    type: Type.MISCELLANEOUS,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Help us improve Wayfarer$/,
    type: Type.SURVEY,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Help us tackle Wayfarer Abuse$/,
    type: Type.SURVEY,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Global Challenge Rewards$/,
    type: Type.CHALLENGE_REWARD,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Your Wayspot submission for/,
    type: Type.NOMINATION_DECIDED,
    style: Style.LIGHTSHIP,
    language: "en",
  },
  {
    subject: /Activated on VPS$/,
    type: Type.MISCELLANEOUS,
    style: Style.LIGHTSHIP,
    language: "en",
  },
  {
    subject: /^Re: \[\d+\] /,
    type: Type.MISCELLANEOUS,
    style: Style.UNKNOWN,
    language: "en",
  },
  //  ---------------------------------------- ENGLISH [en] ----------------------------------------
  {
    subject: /^Thanks! Niantic Wayspot nomination received for/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Niantic Wayspot nomination decided for/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Decision on your? Wayfarer Nomination,/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Thanks! Niantic Wayspot appeal received for/,
    type: Type.NOMINATION_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Your Niantic Wayspot appeal has been decided for/,
    type: Type.NOMINATION_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Thanks! Niantic Wayspot (location|title|description) edit {2}appeal received for/,
    type: Type.EDIT_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Your Niantic Wayspot (location|title|description) edit appeal has been decided for/,
    type: Type.EDIT_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Portal submission confirmation:/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Portal review complete:/,
    type: Type.NOMINATION_DECIDED,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Ingress Portal Submitted:/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.REDACTED,
    language: "en",
  },
  {
    subject: /^Ingress Portal Duplicate:/,
    type: Type.NOMINATION_DECIDED,
    style: Style.REDACTED,
    language: "en",
  },
  {
    subject: /^Ingress Portal Live:/,
    type: Type.NOMINATION_DECIDED,
    style: Style.REDACTED,
    language: "en",
  },
  {
    subject: /^Ingress Portal Rejected:/,
    type: Type.NOMINATION_DECIDED,
    style: Style.REDACTED,
    language: "en",
  },
  {
    subject: /^Trainer [^:]+: Thank You for Nominating a PokéStop for Review.$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Trainer [^:]+: Your PokéStop Nomination Is Eligible!$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Trainer [^:]+: Your PokéStop Nomination Is Ineligible$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Trainer [^:]+: Your PokéStop Nomination Review Is Complete:/,
    type: Type.NOMINATION_DECIDED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Photo Submission Received$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Photo Submission (Accepted|Rejected)$/,
    type: Type.PHOTO_DECIDED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Edit Suggestion Received$/,
    type: Type.EDIT_RECEIVED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Edit Suggestion (Accepted|Rejected)$/,
    type: Type.EDIT_DECIDED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Invalid Pokéstop\/Gym Report Received$/,
    type: Type.REPORT_RECEIVED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Invalid Pokéstop\/Gym Report (Accepted|Rejected)$/,
    type: Type.REPORT_DECIDED,
    style: Style.POKEMON_GO,
    language: "en",
  },
  {
    subject: /^Thanks! Niantic Wayspot Photo received for/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Niantic Wayspot media submission decided for/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Thanks! Niantic Wayspot edit suggestion received for/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Niantic Wayspot edit suggestion decided for/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Thanks! Niantic (Wayspot|location) report received for/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Niantic (Wayspot|location) report decided for/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "en",
  },
  {
    subject: /^Portal photo submission confirmation/,
    type: Type.PHOTO_RECEIVED,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Portal photo review complete/,
    type: Type.PHOTO_DECIDED,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Portal Edit Suggestion Received$/,
    type: Type.EDIT_RECEIVED,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Portal edit submission confirmation/,
    type: Type.EDIT_RECEIVED,
    style: Style.REDACTED,
    language: "en",
  },
  {
    subject: /^Portal edit review complete/,
    type: Type.EDIT_DECIDED,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Invalid Ingress Portal report received$/,
    type: Type.REPORT_RECEIVED,
    style: Style.INGRESS,
    language: "en",
  },
  {
    subject: /^Invalid Ingress Portal report reviewed$/,
    type: Type.REPORT_DECIDED,
    style: Style.INGRESS,
    language: "en",
  },
  //  ---------------------------------------- BENGALI [bn] ----------------------------------------
  {
    subject: /^ধন্যবাদ! .*-এর জন্য Niantic Wayspot মনোনয়ন পাওয়া গেছে!/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "bn",
  },
  {
    subject: /-এর জন্য Niantic Wayspot মনোনয়নের সিদ্ধান্ত নেওয়া হয়েছে/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "bn",
  },
  {
    subject: /^ধন্যবাদ! .*( |-)এর জন্য Niantic Wayspot Photo পাওয়া গিয়েছে!$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "bn",
  },
  {
    subject: /-এর জন্য Niantic Wayspot মিডিয়া জমা দেওয়ার সিদ্ধান্ত নেওয়া হয়েছে$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "bn",
  },
  {
    subject: /^ধন্যবাদ! .*( |-)এর জন্য Niantic Wayspot সম্পাদনা করার পরামর্শ পাওয়া গেছে!$/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "bn",
  },
  {
    subject: /-এর জন্য Niantic Wayspot সম্পাদনায় পরামর্শের সিদ্ধান্ত নেওয়া হয়েছে$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "bn",
  },
  {
    subject: /^ধন্যবাদ! .*( |-)এর জন্য Niantic Wayspot রিপোর্ট পাওয়া গেছে!$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "bn",
  },
  {
    subject: /^Niantic Wayspot রিপোর্ট .*-এর জন্য সিদ্ধান্ত নেওয়া হয়েছে$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "bn",
  },
  //  ---------------------------------------- CZECH [cs] ----------------------------------------
  {
    subject: /^Děkujeme! Přijali jsme nominaci na Niantic Wayspot pro/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Rozhodnutí o nominaci na Niantic Wayspot pro/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Děkujeme! Přijali jsme odvolání proti odmítnutí Niantic Wayspotu/,
    type: Type.NOMINATION_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Rozhodnutí o odvolání proti nominaci na Niantic Wayspot pro/,
    type: Type.NOMINATION_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Děkujeme! Přijali jsme Photo pro Niantic Wayspot/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Rozhodnutí o odeslání obrázku Niantic Wayspotu/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Děkujeme! Přijali jsme návrh na úpravu Niantic Wayspotu pro/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Rozhodnutí o návrhu úpravy Niantic Wayspotu pro/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Děkujeme! Přijali jsme hlášení ohledně Niantic Wayspotu/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "cs",
  },
  {
    subject: /^Rozhodnutí o hlášení v souvislosti s Niantic Wayspotem/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "cs",
  },
  //  ---------------------------------------- GERMAN [de] ----------------------------------------
  {
    subject: /^Danke! Wir haben deinen Vorschlag für den Wayspot/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Entscheidung zum Wayspot-Vorschlag/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Danke! Wir haben deinen Einspruch für den Wayspot/,
    type: Type.NOMINATION_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Entscheidung zum Einspruch für den Wayspot/,
    type: Type.NOMINATION_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Empfangsbestätigung deines eingereichten Portalvorschlags:/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.INGRESS,
    language: "de",
  },
  {
    subject: /^Überprüfung des Portals abgeschlossen:/,
    type: Type.NOMINATION_DECIDED,
    style: Style.INGRESS,
    language: "de",
  },
  {
    subject: /^Trainer [^:]+: Danke, dass du einen PokéStop zur Überprüfung vorgeschlagen hast$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Trainer [^:]+: Dein vorgeschlagener PokéStop ist (zulässig!|nicht zulässig)$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Trainer [^:]+: Die Prüfung deines PokéStop-Vorschlags wurde abgeschlossen:/,
    type: Type.NOMINATION_DECIDED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Fotovorschlag erhalten$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Fotovorschlag (akzeptiert|abgelehnt)$/,
    type: Type.PHOTO_DECIDED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Vorschlag für Bearbeitung erhalten$/,
    type: Type.EDIT_RECEIVED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Vorschlag für Bearbeitung (akzeptiert|abgelehnt)$/,
    type: Type.EDIT_DECIDED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Meldung zu unzulässigen PokéStop\/Arena erhalten$/,
    type: Type.REPORT_RECEIVED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Meldung zu unzulässigen PokéStop\/Arena (akzeptiert|abgelehnt)$/,
    type: Type.REPORT_DECIDED,
    style: Style.POKEMON_GO,
    language: "de",
  },
  {
    subject: /^Danke! Wir haben den Upload Photo für den Wayspot/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Entscheidung zu deinem Upload für den Wayspot/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Danke! Wir haben deinen Änderungsvorschlag für den Wayspot/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Entscheidung zu deinem Änderungsvorschlag für den Wayspot/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Danke! Wir haben deine Meldung für den Wayspot/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Entscheidung zu deiner Meldung für den Wayspot/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "de",
  },
  {
    subject: /^Portalfotovorschlag erhalten/,
    type: Type.PHOTO_RECEIVED,
    style: Style.INGRESS,
    language: "de",
  },
  {
    subject: /^Überprüfung des Portalfotos abgeschlossen/,
    type: Type.PHOTO_DECIDED,
    style: Style.INGRESS,
    language: "de",
  },
  {
    subject: /^Vorschlag für die Änderung eines Portals erhalten/,
    type: Type.EDIT_RECEIVED,
    style: Style.INGRESS,
    language: "de",
  },
  {
    subject: /^Überprüfung des Vorschlags zur Änderung eines Portals abgeschlossen/,
    type: Type.EDIT_DECIDED,
    style: Style.INGRESS,
    language: "de",
  },
  {
    subject: /^Meldung zu ungültigem Ingress-Portal erhalten$/,
    type: Type.REPORT_RECEIVED,
    style: Style.INGRESS,
    language: "de",
  },
  {
    subject: /^Meldung zu ungültigem Ingress-Portal geprüft$/,
    type: Type.REPORT_DECIDED,
    style: Style.INGRESS,
    language: "de",
  },
  //  ---------------------------------------- SPANISH [es] ----------------------------------------
  {
    subject: /^¡Gracias! ¡Hemos recibido la propuesta de Wayspot de Niantic/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^Decisión tomada sobre la propuesta de Wayspot de Niantic/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^¡Gracias! ¡Recurso de Wayspot de Niantic recibido para/,
    type: Type.NOMINATION_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^¡Gracias! ¡Hemos recibido el Photo del Wayspot de Niantic para/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^Decisión tomada sobre el envío de archivo de Wayspot de Niantic para/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^¡Gracias! ¡Propuesta de modificación de Wayspot de Niantic recibida para/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^Decisión tomada sobre la propuesta de modificación del Wayspot de Niantic/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^¡Gracias! ¡Hemos recibido el informe sobre el Wayspot de Niantic/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "es",
  },
  {
    subject: /^Decisión tomada sobre el Wayspot de Niantic/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "es",
  },
  //  ---------------------------------------- FRENCH [fr] ----------------------------------------
  {
    subject: /^Remerciements ! Proposition d’un Wayspot Niantic reçue pour/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "fr",
  },
  {
    subject: /^Résultat concernant la proposition du Wayspot Niantic/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "fr",
  },
  {
    subject: /^Remerciements ! Contribution de Wayspot Niantic Photo reçue pour/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "fr",
  },
  {
    subject: /^Résultat concernant le Wayspot Niantic/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "fr",
  },
  {
    subject: /^Remerciements ! Proposition de modification de Wayspot Niantic reçue pour/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "fr",
  },
  {
    subject: /^Résultat concernant la modification du Wayspot Niantic/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "fr",
  },
  {
    subject: /^Remerciements ! Signalement reçu pour le Wayspot/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "fr",
  },
  {
    subject: /^Résultat concernant le signalement du Wayspot Niantic/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "fr",
  },
  //  ---------------------------------------- HINDI [hi] ----------------------------------------
  {
    subject: /^धन्यवाद! .* के लिए Niantic Wayspot नामांकन प्राप्त हुआ!$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "hi",
  },
  {
    subject: /^Niantic Wayspot का नामांकन .* के लिए तय किया गया$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "hi",
  },
  {
    subject: /के लिए तह Niantic Wayspot मीडिया सबमिशन$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "hi",
  },
  {
    subject: /^धन्यवाद! .* के लिए Niantic Wayspot Photo प्राप्त हुआ!$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "hi",
  },
  {
    subject: /^धन्यवाद! .* के लिए Niantic Wayspot संपादन सुझाव प्राप्त हुआ!$/,
    disambiguate: (email: Email) => {
      const doc = email.getDocument();
      const title = doc?.querySelector("td.em_pbottom.em_blue.em_font_20")?.textContent.trim();
      if (title == "बढ़िया खोज की! आपके वेस्पॉट Photo सबमिशन के लिए धन्यवाद!") {
        return {
          type: Type.PHOTO_RECEIVED,
          style: Style.WAYFARER,
          language: "hi",
        };
      } else if (title?.includes("आपके संपादन हमारे खोजकर्ताओं के समुदाय के लिए सर्वोत्तम संभव अनुभव बनाए रखने में मदद करते हैं।")) {
        return {
          type: Type.EDIT_RECEIVED,
          style: Style.WAYFARER,
          language: "hi",
        };
      } else {
        return null;
      }
    },
  },
  {
    subject: /के लिए Niantic Wayspot संपादन सुझाव प्राप्त हुआ$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "hi",
  },
  {
    subject: /^धन्यवाद! .* के लिए प्राप्त Niantic Wayspot रिपोर्ट!$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "hi",
  },
  {
    subject: /के लिए तय Niantic Wayspot रिपोर्ट$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "hi",
  },
  //  ---------------------------------------- ITALIAN [it] ----------------------------------------
  {
    subject: /^Grazie! Abbiamo ricevuto una candidatura di Niantic Wayspot per/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "it",
  },
  {
    subject: /^Proposta di Niantic Wayspot decisa per/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "it",
  },
  {
    subject: /^Grazie! Abbiamo ricevuto Photo di Niantic Wayspot per/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "it",
  },
  {
    subject: /^Proposta di contenuti multimediali di Niantic Wayspot decisa per/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "it",
  },
  {
    subject: /^Grazie! Abbiamo ricevuto il suggerimento di modifica di Niantic Wayspot per/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "it",
  },
  {
    subject: /^Suggerimento di modifica di Niantic Wayspot deciso per/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "it",
  },
  {
    subject: /^Grazie! Abbiamo ricevuto la segnalazione di Niantic Wayspot per/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "it",
  },
  {
    subject: /^Segnalazione di Niantic Wayspot decisa per/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "it",
  },
  //  ---------------------------------------- JAPANESE [ja] ----------------------------------------
  {
    subject: /^ありがとうございます。 Niantic Wayspotの申請「.*」が受領されました。$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^Niantic Wayspotの申請「.*」が決定しました。$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^ありがとうございます。 Niantic Wayspotに関する申し立て「.*」が受領されました。$/,
    type: Type.NOMINATION_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^Niantic Wayspot「.*」に関する申し立てが決定しました。$/,
    type: Type.NOMINATION_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^ありがとうございます。 Niantic Wayspot Photo「.*」が受領されました。$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^Niantic Wayspotのメディア申請「.*」が決定しました。$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^ありがとうございます。 Niantic Wayspot「.*」の編集提案が受領されました。$/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^Niantic Wayspotの編集提案「.*」が決定しました。$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^ありがとうございます。 Niantic Wayspotに関する報告「.*」が受領されました。$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "ja",
  },
  {
    subject: /^Niantic Wayspotの報告「.*」が決定しました$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "ja",
  },
  //  ---------------------------------------- KOREAN [ko] ----------------------------------------
  {
    subject: /^감사합니다! .*에 대한 Niantic Wayspot 후보 신청이 완료되었습니다!$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "ko",
  },
  {
    subject: /에 대한 Niantic Wayspot 후보 결정이 완료됨$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "ko",
  },
  {
    subject: /^감사합니다! .*에 대한 Niantic Wayspot Photo 제출 완료$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "ko",
  },
  {
    subject: /에 대한 Niantic Wayspot 미디어 제안 결정 완료$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "ko",
  },
  {
    subject: /^감사합니다! .*에 대한 Niantic Wayspot 수정이 제안되었습니다!$/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "ko",
  },
  {
    subject: /에 대한 Niantic Wayspot 수정 제안 결정 완료$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "ko",
  },
  {
    subject: /^감사합니다! .*에 대한 Niantic Wayspot 보고 접수$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "ko",
  },
  {
    subject: /에 대한 Niantic Wayspot 보고 결정 완료$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "ko",
  },
  //  ---------------------------------------- MARATHI [mr] ----------------------------------------
  {
    subject: /^धन्यवाद! Niantic वेस्पॉट नामांकन .* साठी प्राप्त झाले!$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /^Niantic वेस्पॉट नामांकन .* साठी निश्चित केले$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /^धन्यवाद! Niantic वेस्पॉट आवाहन .* साठी प्राप्त झाले!$/,
    type: Type.NOMINATION_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /^तुमचे Niantic वेस्पॉट आवाहन .* साठी निश्चित करण्यात आले आहे$/,
    type: Type.NOMINATION_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /^धन्यवाद! .* साठी Niantic वेस्पॉट Photo प्राप्त झाले!$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /साठी Niantic वेस्पॉट मीडिया सबमिशनचा निर्णय घेतला$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /^धन्यवाद! Niantic वेस्पॉट संपादन सूचना .* साठी प्राप्त झाली!$/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /^Niantic वेस्पॉट संपादन सूचना .* साठी निश्चित केली$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /^धन्यवाद! .* साठी Niantic वेस्पॉट अहवाल प्राप्त झाला!$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "mr",
  },
  {
    subject: /साठी Niantic वेस्पॉट अहवाल निश्चित केला$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "mr",
  },
  //  ---------------------------------------- DUTCH [nl] ----------------------------------------
  {
    subject: /^Bedankt! Niantic Wayspot-nominatie ontvangen voor/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "nl",
  },
  {
    subject: /^Besluit over Niantic Wayspot-nominatie voor/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "nl",
  },
  {
    subject: /^Bedankt! Niantic Wayspot-Photo ontvangen voor/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "nl",
  },
  {
    subject: /^Besluit over Niantic Wayspot-media-inzending voor/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "nl",
  },
  {
    subject: /^Bedankt! Niantic Wayspot-bewerksuggestie ontvangen voor/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "nl",
  },
  {
    subject: /^Besluit over Niantic Wayspot-bewerksuggestie voor/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "nl",
  },
  {
    subject: /^Bedankt! Melding van Niantic Wayspot .* ontvangen!$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "nl",
  },
  {
    subject: /^Besluit over Niantic Wayspot-melding voor/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "nl",
  },
  //  ---------------------------------------- NORWEGIAN [no] ----------------------------------------
  {
    subject: /^Takk! Vi har mottatt Niantic Wayspot-nominasjonen for/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^En avgjørelse er tatt for Niantic Wayspot-nominasjonen for/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^Takk! Vi har mottatt Niantic Wayspot-klagen for/,
    type: Type.NOMINATION_APPEAL_RECEIVED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^En avgjørelse er tatt for Niantic Wayspot-klagen for/,
    type: Type.NOMINATION_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^Takk! Vi har mottatt Photo for Niantic-Wayspot-en/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^Takk! Vi har mottatt endringsforslaget for Niantic Wayspot-en/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^Takk! Vi har mottatt Niantic Wayspot-rapporten for/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^En avgjørelse er tatt for Niantic Wayspot-medieinnholdet som er sendt inn for/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^En avgjørelse er tatt for endringsforslaget for Niantic Wayspot-en/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "no",
  },
  {
    subject: /^En avgjørelse er tatt for Niantic Wayspot-rapporten for/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "no",
  },
  //  ---------------------------------------- POLISH [pl] ----------------------------------------
  {
    subject: /^Dziękujemy! Odebrano nominację Wayspotu/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "pl",
  },
  {
    subject: /^Podjęto decyzję na temat nominacji Wayspotu/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "pl",
  },
  {
    subject: /^Dziękujemy! Odebrano materiały Photo Wayspotu Niantic/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "pl",
  },
  {
    subject: /^Decyzja na temat zgłoszenia materiałów do Wayspotu Niantic/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "pl",
  },
  {
    subject: /^Dziękujemy! Odebrano sugestię zmiany Wayspotu Niantic/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "pl",
  },
  {
    subject: /^Podjęto decyzję na temat sugestii edycji Wayspotu Niantic/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "pl",
  },
  {
    subject: /^Dziękujemy! Odebrano raport dotyczący Wayspotu Niantic/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "pl",
  },
  {
    subject: /^Podjęto decyzję odnośnie raportu dotyczącego Wayspotu Niantic/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "pl",
  },
  //  ---------------------------------------- PORTUGUESE [pt] ----------------------------------------
  {
    subject: /^Agradecemos a sua indicação para o Niantic Wayspot/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "pt",
  },
  {
    subject: /^Decisão sobre a indicação do Niantic Wayspot/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "pt",
  },
  {
    subject: /^Agradecemos o envio de Photo para o Niantic Wayspot/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "pt",
  },
  {
    subject: /^Decisão sobre o envio de mídia para o Niantic Wayspot/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "pt",
  },
  {
    subject: /^Agradecemos a sua sugestão de edição para o Niantic Wayspot/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "pt",
  },
  {
    subject: /^Decisão sobre a sugestão de edição do Niantic Wayspot/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "pt",
  },
  {
    subject: /^Agradecemos o envio da denúncia referente ao Niantic Wayspot/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "pt",
  },
  {
    subject: /^Decisão sobre a denúncia referente ao Niantic Wayspot/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "pt",
  },
  //  ---------------------------------------- RUSSIAN [ru] ----------------------------------------
  {
    subject: /^Спасибо! Номинация Niantic Wayspot для .* получена!$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "ru",
  },
  {
    subject: /^Вынесено решение по номинации Niantic Wayspot для/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "ru",
  },
  {
    subject: /^Спасибо! Получено: Photo Niantic Wayspot для/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "ru",
  },
  {
    subject: /^Вынесено решение по предложению по файлу для/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "ru",
  },
  {
    subject: /^Спасибо! Предложение по изменению Niantic Wayspot для/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "ru",
  },
  {
    subject: /^Вынесено решение по предложению по изменению Niantic Wayspot для/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "ru",
  },
  {
    subject: /^Спасибо! Жалоба на Niantic Wayspot для/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "ru",
  },
  {
    subject: /^Вынесено решение по жалобе на Niantic Wayspot для/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "ru",
  },
  //  ---------------------------------------- SWEDISH [sv] ----------------------------------------
  {
    subject: /^Tack! Niantic Wayspot-nominering har tagits emot för/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Niantic Wayspot-nominering har beslutats om för/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Din Niantic Wayspot-överklagan har beslutats om för/,
    type: Type.NOMINATION_APPEAL_DECIDED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Tack! Niantic Wayspot Photo togs emot för/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Niantic Wayspot-medieinlämning har beslutats om för/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Tack! Niantic Wayspot-redigeringsförslag har tagits emot för/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Niantic Wayspot-redigeringsförslag har beslutats om för/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Tack! Niantic Wayspot-rapport har tagits emot för/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "sv",
  },
  {
    subject: /^Niantic Wayspot-rapport har beslutats om för/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "sv",
  },
  //  ---------------------------------------- TAMIL [ta] ----------------------------------------
  {
    subject: /^நன்றி! .* -க்கான Niantic Wayspot பரிந்துரை பெறப்பட்டது!!$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "ta",
  },
  {
    subject: /-க்கான Niantic Wayspot பணிந்துரை பரிசீலிக்கப்பட்டது.$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "ta",
  },
  {
    subject: /^நன்றி! .* -க்கான Niantic Wayspot Photo பெறப்பட்டது!$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "ta",
  },
  {
    subject: /-க்கான Niantic Wayspot மீடியா சமர்ப்பிப்பு பரிசீலிக்கப்பட்டது.$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "ta",
  },
  {
    subject: /^நன்றி! .* -க்கான Niantic Wayspot திருத்த பரிந்துரை பெறப்பட்டது!$/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "ta",
  },
  {
    subject: /-க்கான Niantic Wayspot திருத்த பரிந்துரை பரிசீலிக்கப்பட்டது$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "ta",
  },
  {
    subject: /^நன்றி! .* -க்கான Niantic Wayspot புகார் பெறப்பட்டது!$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "ta",
  },
  {
    subject: /-க்கான Niantic Wayspot புகார் பரிசீலிக்கப்பட்டது!$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "ta",
  },
  //  ---------------------------------------- TELUGU [te] ----------------------------------------
  {
    subject: /^ధన్యవాదాలు! .* కు Niantic Wayspot నామినేషన్ అందుకున్నాము!$/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "te",
  },
  {
    subject: /కొరకు Niantic వేస్పాట్ నామినేషన్‌‌పై నిర్ణయం$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "te",
  },
  {
    subject: /^ధన్యవాదాలు! .* కొరకు Niantic Wayspot Photo అందుకున్నాము!$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "te",
  },
  {
    subject: /కొరకు Niantic వేస్పాట్ మీడియా సమర్పణపై నిర్ణయం$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "te",
  },
  {
    subject: /^ధన్యవాదాలు! మీ వేస్పాట్ .* ఎడిట్ సూచనకై ధన్యవాదాలు!$/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "te",
  },
  {
    subject: /కొరకు నిర్ణయించబడిన Niantic వేస్పాట్ సూచన$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "te",
  },
  {
    subject: /^ధన్యవాదాలు! .* కొరకు Niantic వేస్పాట్ నామినేషన్ అందుకున్నాము!$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "te",
  },
  {
    subject: /కొరకు నిర్ణయించబడిన Niantic వేస్పాట్ రిపోర్ట్$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "te",
  },
  //  ---------------------------------------- THAI [th] ----------------------------------------
  {
    subject: /^ขอบคุณ! เราได้รับการเสนอสถานที่ Niantic Wayspot สำหรับ/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "th",
  },
  {
    subject: /^ผลการตัดสินการเสนอสถานที่ Niantic Wayspot สำหรับ/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "th",
  },
  {
    subject: /^ขอบคุณ! ได้รับ Niantic Wayspot Photo สำหรับ/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "th",
  },
  {
    subject: /^ผลการตัดสินการส่งมีเดีย Niantic Wayspot สำหรับ/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "th",
  },
  {
    subject: /^ขอบคุณ! เราได้รับคำแนะนำการแก้ไข Niantic Wayspot สำหรับ/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "th",
  },
  {
    subject: /^ผลการตัดสินคำแนะนำการแก้ไข Niantic Wayspot สำหรับ/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "th",
  },
  {
    subject: /^ขอบคุณ! เราได้รับการรายงาน Niantic Wayspot สำหรับ/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "th",
  },
  {
    subject: /^ผลตัดสินการรายงาน Niantic Wayspot สำหรับ/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "th",
  },
  //  ---------------------------------------- CHINESE [zh] ----------------------------------------
  {
    subject: /^感謝你！ 我們已收到 Niantic Wayspot 候選/,
    type: Type.NOMINATION_RECEIVED,
    style: Style.WAYFARER,
    language: "zh",
  },
  {
    subject: /^社群已對 Niantic Wayspot 候選 .* 做出決定$/,
    type: Type.NOMINATION_DECIDED,
    style: Style.WAYFARER,
    language: "zh",
  },
  {
    subject: /^感謝你！ 我們已收到 .* 的 Niantic Wayspot Photo！$/,
    type: Type.PHOTO_RECEIVED,
    style: Style.WAYFARER,
    language: "zh",
  },
  {
    subject: /^社群已對你為 .* 提交的 Niantic Wayspot 媒體做出決定$/,
    type: Type.PHOTO_DECIDED,
    style: Style.WAYFARER,
    language: "zh",
  },
  {
    subject: /^感謝你！ 我們已收到 .* 的 Niantic Wayspot 編輯建議！$/,
    type: Type.EDIT_RECEIVED,
    style: Style.WAYFARER,
    language: "zh",
  },
  {
    subject: /^社群已對 .* 的 Niantic Wayspot 編輯建議做出決定$/,
    type: Type.EDIT_DECIDED,
    style: Style.WAYFARER,
    language: "zh",
  },
  {
    subject: /^感謝你！ 我們已收到 .* 的 Niantic Wayspot 報告！$/,
    type: Type.REPORT_RECEIVED,
    style: Style.WAYFARER,
    language: "zh",
  },
  {
    subject: /^Niantic 已對 .* 的 Wayspot 報告做出決定$/,
    type: Type.REPORT_DECIDED,
    style: Style.WAYFARER,
    language: "zh",
  },
];

export default TEMPLATES;
