# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: 26.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build-prod
    - name: Upload scripts
      uses: actions/upload-artifact@v7
      with:
        name: dist
        path: dist/*
        overwrite: true
    - name: Upload assets
      uses: actions/upload-artifact@v7
      with:
        name: resources
        path: resources/*
        overwrite: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download scripts
      uses: actions/download-artifact@v7
      with:
        name: dist
        path: dist
    - name: Download assets
      uses: actions/download-artifact@v7
      with:
        name: resources
        path: resources
    - name: Publish scripts and assets
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ vars.SSH_KNOWN_HOSTS }}
        SSH_TARGET: ${{ vars.SSH_TARGET }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_ed25519 ~/.ssh/known_hosts
        scp dist/* "${SSH_TARGET}:dist/"
        scp resources/* "${SSH_TARGET}:assets/"
